data:
  in_memory: 1
  num_workers: 12
dist:
  world_size: 8
logging:
  folder: /tmp/
lr:
  lr: 1.7
  lr_schedule_type: cyclic
model:
  arch: resnet50
resolution:
  end_ramp: 85
  max_res: 192
  min_res: 160
  start_ramp: 70
training:
  batch_size: 256
  bn_wd: 0
  distributed: 1
  epochs: 100
  label_smoothing: 0
  momentum: 0.9
  optimizer: "adamw"
  weight_decay: 0.0001
  use_blurpool: 0
validation:
  lr_tta: False
  resolution: 256
